version: "3.7"
services:
  web:
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - SERVER_PORT=3000
      - MYSQL_HOST=dbMysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=blog
      - BCRYPT_SALT=10
      - SECRET_KEY=secretkey
    ports:
      - "3001:3000"
    depends_on:
      - dbMysql
  dbMysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./dist/database:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
 
